export const TAB_CHANGE = 'TAB_CHANGE';
export const VIEW_CHANGE = 'VIEW_CHANGE';
export const SIDEBAR_OPENED = 'SIDEBAR_OPENED';
export const USER_LOGIN_STATUS = 'USER_LOGIN_STATUS';
export const USER_INFO = 'USER_INFO';
export const USER_PROFILE_SETTINGS = 'USER_PROFILE_SETTINGS';
export const SITE_INFO = 'SITE_INFO';